spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cooksysyem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
